name: AbleSci Auto Sign

on:
  workflow_dispatch:
  schedule:
    - cron: '40 8,18 * * *'  # UTC时间(北京时间为21:40和次日7:40)

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AbleSci Sign
        id: sign
        run: |
          python ablesci.py > output.log
          LOG_CONTENT=$(cat output.log)
          echo "LOG_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$LOG_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          GITHUB_ACTIONS: true
          ABLESCI_ACCOUNTS: ${{ secrets.ABLESCI_ACCOUNTS }}
          # 选择一种通知服务
          # SCKEY: ${{ secrets.SCKEY }}          # Server酱
          # XZKEY: ${{ secrets.XZKEY }}        # 息知 (按需启用)
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }} # PushPlus (按需启用)

      - name: Display Log
        run: |
          echo "$LOG_CONTENT"
